# Generated by Django 2.0.2 on 2018-07-31 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_auto_20180731_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
