# Generated by Django 2.0.2 on 2018-08-02 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_auto_20180731_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='date',
            field=models.DateTimeField(default=datetime.date(2018, 8, 1)),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='date',
            field=models.DateTimeField(default=datetime.date(2018, 8, 1)),
        ),
    ]
